import assert from 'node:assert/strict';
import test from 'node:test';
process.env.DATABASE_URL = 'postgresql://test:test@localhost:5432/test';
import { isCalendarDate, isDiaryId, readDiaryInput, readDiaryRange, withDiaryOwner } from './diaryValidation';

const valid = { workDate: '2026-08-30', title: 'Inspect suspension', workPerformed: 'Checked pressures and valves.', followUpRequired: false, tags: [], startTime: null, endTime: null, durationMinutes: null, craneModel: null, craneId: null, systemCategory: null, faultSymptom: null, diagnosis: null, partsUsed: null, outcome: null, followUpNotes: null, documentId: null, workshopNoteId: null };
test('calendar dates handle leap days and reject impossible or malformed dates', () => { assert.equal(isCalendarDate('2024-02-29'), true); assert.equal(isCalendarDate('2026-02-29'), false); assert.equal(isCalendarDate('2026-02-28'), true); assert.equal(isCalendarDate('2026-02-30'), false); assert.equal(isCalendarDate('30-08-2026'), false); });
test('diary input validates required fields and practical limits', () => { assert.ok(readDiaryInput(valid)); assert.equal(readDiaryInput({ ...valid, title: '' }), null); assert.equal(readDiaryInput({ ...valid, workPerformed: 'x'.repeat(20_001) }), null); assert.equal(readDiaryInput({ ...valid, durationMinutes: 10_081 }), null); });
test('date ranges allow exactly 732 days and reject 733 days or reversed ranges', () => { assert.deepEqual(readDiaryRange('2024-09-01', '2026-09-02'), { from: '2024-09-01', to: '2026-09-02' }); assert.equal(readDiaryRange('2024-09-01', '2026-09-03'), null); assert.equal(readDiaryRange('2026-09-01', '2026-08-31'), null); });
test('ownership always comes from the authenticated technician', () => { const input = readDiaryInput({ ...valid, technicianId: 'attacker' }); assert.ok(input); assert.equal('technicianId' in input, false); assert.equal(withDiaryOwner(input, 'authenticated-owner').technicianId, 'authenticated-owner'); });
test('malformed diary IDs are rejected before mutation lookup', () => { assert.equal(isDiaryId('not-an-id'), false); assert.equal(isDiaryId('00000000-0000-4000-8000-000000000001'), true); });
test('diary routes authenticate reads and protect every mutation with same-origin checks', async () => { const { default: router } = await import('../routes/diary'); const { requireAuth } = await import('../middleware/auth'); const { requireSameOrigin } = await import('../middleware/sameOrigin'); const routes = (router as unknown as { stack: Array<{ route?: { path: string; methods: Record<string, boolean>; stack: Array<{ handle: unknown }> } }> }).stack.map((layer) => layer.route).filter(Boolean); const get = routes.find((route) => route?.methods.get); assert.equal(get?.stack[0]?.handle, requireAuth); for (const route of routes.filter((item) => item && !item.methods.get)) { assert.equal(route?.stack[0]?.handle, requireAuth); assert.equal(route?.stack[1]?.handle, requireSameOrigin); } });
